#!/bin/bash

# JankyBorders configuration
# Colors match Sonokai theme used in sketchybar

options=(
	style=round
	width=8.0
	hidpi=off
	active_color=0xff76cce0
	inactive_color=0xff414550
)

borders "${options[@]}"
